config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  resources :beauties
  resources :smarts
  resources :cools
  resources :toughs

   root 'welcome#index'

end

app/models/beauty.rb
class Beauty < ActiveRecord::Base
end

app/models/cool.rb
class Cool < ActiveRecord::Base
end

app/models/smart.rb
class Smart < ActiveRecord::Base
end

app/models/tough.rb
class Tough < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beauties_controller.rb
class BeautiesController < ApplicationController
  def index
    @beauties = Beauty.all
  end

  def show
    @beauty = Beauty.find(params[:id])
  end

  def new
  end
 
  def edit
    @beauty = Beauty.find(params[:id])
  end
  
  def create
     @beauty = Beauty.new(beauty_params)
 
     @beauty.save
     redirect_to @beauty
  end

  def update
    @beauty = Beauty.find(params[:id])
 
    if @beauty.update(beauty_params)
      redirect_to @beauty
    else
      render 'edit'
    end
  end

  def destroy
    @beauty = Beauty.find(params[:id])
    @beauty.destroy
 
    redirect_to beauties_path
  end

  private
    def beauty_params
      params.require(:beauty).permit(:pokemon, :trainer, :type1, :type2, :type3, :type4, :move1, :move2, :move3, :move4, :weakness1, :weakness2, :evolution1, :evolution2, :evolution3)
    end

end

app/controllers/cools_controller.rb
class CoolsController < ApplicationController
  def index
    @cools = Cool.all
  end

  def show
    @cool = Cool.find(params[:id])
  end

  def new
  end
 
  def edit
    @cool = Cool.find(params[:id])
  end
  
  def create
     @cool = Cool.new(cool_params)
 
     @cool.save
     redirect_to @cool
  end

  def update
    @cool = Cool.find(params[:id])
 
    if @cool.update(cool_params)
      redirect_to @cool
    else
      render 'edit'
    end
  end

  def destroy
    @cool = Cool.find(params[:id])
    @cool.destroy
 
    redirect_to cools_path
  end

  private
    def cool_params
      params.require(:cool).permit(:pokemon, :trainer, :type1, :type2, :type3, :type4, :move1, :move2, :move3, :move4, :weakness1, :weakness2, :evolution1, :evolution2, :evolution3)
    end
end

  

app/controllers/smarts_controller.rb
class SmartsController < ApplicationController
  def index
    @smarts = Smart.all
  end

  def show
    @smart = Smart.find(params[:id])
  end

  def new
  end
 
  def edit
    @smart = Smart.find(params[:id])
  end

  def create
     @smart = Smart.new(smart_params)
 
     @smart.save
     redirect_to @smart
  end

  def update
    @smart = Smart.find(params[:id])
 
    if @smart.update(smart_params)
      redirect_to @smart
    else
      render 'edit'
    end
  end

  def destroy
    @smart = Beauty.find(params[:id])
    @smart.destroy
 
    redirect_to beauties_path
  end

  private
    def smart_params
      params.require(:smart).permit(:pokemon, :trainer, :type1, :type2, :type3, :type4, :move1, :move2, :move3, :move4, :weakness1, :weakness2, :evolution1, :evolution2, :evolution3)
    end
end

app/controllers/toughs_controller.rb
class ToughsController < ApplicationController
  def index
    @toughs = Tough.all
  end

  def show
    @tough = Tough.find(params[:id])
  end

  def new
  end
 
  def edit
    @tough = Tough.find(params[:id])
  end
  
  def create
     @tough = Tough.new(tough_params)
 
     @tough.save
     redirect_to @tough
  end

  def update
    @tough = Tough.find(params[:id])
 
    if @tough.update(tough_params)
      redirect_to @tough
    else
      render 'edit'
    end
  end

  def destroy
    @tough = Tough.find(params[:id])
    @tough.destroy
 
    redirect_to toughs_path
  end

  private
    def tough_params
      params.require(:tough).permit(:pokemon, :trainer, :type1, :type2, :type3, :type4, :move1, :move2, :move3, :move4, :weakness1, :weakness2, :evolution1, :evolution2, :evolution3)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beauties_helper.rb
module BeautiesHelper
end

app/helpers/cools_helper.rb
module CoolsHelper
end

app/helpers/smarts_helper.rb
module SmartsHelper
end

app/helpers/toughs_helper.rb
module ToughsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/beauties/edit.html.erb
<div class="div_setting">
     <div class="main">
          <%= form_for :beauty, url: beauty_path(@beauty), method: :patch do |f| %>
          <div class="sub_top">
               <%= link_to 'Pokemon List', beauties_path,class:"button_link left"%>
               <%= f.submit "Save", class:"button_link right"%>         
          </div>
         
          <div class="sub_bottom">
               <div class="sub_left">
                    <img src="c.png" class="pokemon_profile"/>
                    <p class="p_title">Pokemon</p>
                    <center>
                         <%= f.text_field :pokemon, class:'p_input p_border add_mb20' %>
                    </center>
                    <p class="p_title">Trainer</p>
                    <center>
                         <%= f.text_field :trainer,class:"p_input p_border" %>
                    </center>
               </div>

               <div class="sub_right">
                    <p class="p_title add_mt20">Types</p>
                         <%= f.text_field :type1, class:"p2_input p_border m_b", placeholder:"1 (required)" %>
                         <%= f.text_field :type2, class:"p2_input p_border m_b", placeholder:"2" %>
                    
                    <p class="p_title add_mt20">Moves</p>
                         <%= f.text_field :move1, class:"p2_input p_border", placeholder:"1 (required)" %>
                         <%= f.text_field :move2, class:"p2_input p_border", placeholder:"2" %>
                         <%= f.text_field :move3, class:"p2_input p_border m_b", placeholder:"3" %>
                         <%= f.text_field :move4, class:"p2_input p_border m_b", placeholder:"4" %>

                    <p class="p_title add_mt20">Weakness</p>
                         <%= f.text_field :weakness1, class:"p2_input p_border m_b", placeholder:"1 (required)" %>
                         <%= f.text_field :weakness2, class:"p2_input p_border m_b", placeholder:"1" %>
                    
                    <p class="p_title add_mt20">Evolution</p>
                         <%= f.text_field :evolution1, class:"p2_input p_border", placeholder:"1"%>
                         <%= f.text_field :evolution2, class:"p2_input p_border", placeholder:"2"%>
                         <center>
                         <%= f.text_field :evolution3, class:"p2_input p_border m_b", placeholder:"3",style:"float:none" %>
                         </center>
               </div>
          </div>

          <% end %>
     </div>
</div>

app/views/beauties/index.html.erb
<div class="div_setting">
     <div class="main">
          <div class="sub_top">
               <a href="../welcome/index" class="button_link left index_special">Home</a>
               <%= link_to 'Register', new_beauty_path, class:"button_link right index_special"%>
          </div>

          <div class="sub_bottom">
               <div class="p_thead">
                    <span class="p_span" style="padding-left:10px;padding-right:220px;">Pokemon</span>
                    <span class="p_span" style="padding-right:235px;">Trainer</span>
                    <span class="p_span">Action</span>
               </div>
               <div class="sub_table">
               <table class="table table-hover">
                    <tbody>
                         <% @beauties.each do |beauty| %>
                         <tr>
                         <td style="width:5%"><img src="" class="pokemon_profile_small"/></td>
                            <td style="width:32.5%"><%= beauty.pokemon %></td>
                            <td style="width:32.5%"><%= beauty.trainer %></td>
                            <td style="width:30%">
                              <!-- <a href="">Remove</a> -->
                              <%= link_to 'Destroy', beauty_path(beauty),method: :delete,data: { confirm: 'Are you sure?' } %>
                              <!-- <a href="">Edit</a> -->
                              <%= link_to 'Edit', edit_beauty_path(beauty) %>
                              <!-- <a href="">Show</a> -->
                              <%= link_to 'Show', beauty_path(beauty) %>
                            </td>
                         </tr>
                         <% end %>
                    </tbody>
               </table>
               </div>
          </div>
     </div>
</div>

app/views/beauties/show.html.erb
<div class="div_setting">
     <div class="main">
          <div class="sub_top">
               <%= link_to 'Pokemon List', beauties_path,  class:"button_link left"%>
               <%= link_to 'Edit', edit_beauty_path(@beauty), class:"button_link right" %>
          </div>

          <div class="sub_bottom">
               <div class="sub_left">
                    <img src="c.png" class="pokemon_profile"/>
                    <p class="p_title">Pokemon</p>
                    <p class="p_content add_mb20"><%= @beauty.pokemon %></p>
                    <p class="p_title">Trainer</p>
                    <p class="p_content"><%= @beauty.trainer %></p>
               </div>

               <div class="sub_right">
                    <div class="sub_rightcontent">
                         <div class="rightcontent_title p_title add_mb10">Types</div>
                         <div class="rightcontent">
                              <div class="rightcontent_main add_mb30"><%= @beauty.type1 %></div>
                              <div class="rightcontent_main add_mb30"><%= @beauty.type2 %></div>
                         </div>
                    </div>
                    <div class="sub_rightcontent">
                         <div class="rightcontent_title p_title add_mb10">Moves</div>
                         <div class="rightcontent">
                              <div class="rightcontent_main add_mb10"><%= @beauty.move1 %></div>
                              <div class="rightcontent_main add_mb10"><%= @beauty.move2 %></div>
                              <div class="rightcontent_main add_mb30"><%= @beauty.move3 %></div>
                              <div class="rightcontent_main add_mb30"><%= @beauty.move4 %></div>
                         </div>
                    </div>
                    <div class="sub_rightcontent">
                         <div class="rightcontent_title p_title add_mb10">Weaknesses</div>
                         <div class="rightcontent">
                              <div class="rightcontent_main add_mb30"><%= @beauty.weakness1 %></div>
                              <div class="rightcontent_main add_mb30"><%= @beauty.weakness2 %></div>
                         </div>
                    </div>
                    <div class="sub_rightcontent">
                         <div class="rightcontent_title p_title add_mb10">Evolution</div>
                         <div class="rightcontent">
                              <div class="rightcontent_main add_mb10"><%= @beauty.evolution1 %></div>
                              <div class="rightcontent_main add_mb10"><%= @beauty.evolution2 %></div>
                              <div class="rightcontent_main add_mb30"><%= @beauty.evolution3 %></div>
                         </div>
                    </div>
               </div>
          </div>
     </div>
</div>

app/views/cools/edit.html.erb
<div class="div_setting">
     <div class="main">
          
          <%= form_for :cool, url: cool_path(@cool), method: :patch do |f| %>
          
          <div class="sub_top">
               <%= link_to 'Pokemon List', cools_path,class:"button_link left"%>
               <%= f.submit "Save", class:"button_link right"%>         
          </div>
         
          <div class="sub_bottom">
               <div class="sub_left">
                    <img src="c.png" class="pokemon_profile"/>
                    <p class="p_title">Pokemon</p>
                    <center>
                         <%= f.text_field :pokemon, class:'p_input p_border add_mb20' %>
                    </center>
                    <p class="p_title">Trainer</p>
                    <center>
                         <%= f.text_field :trainer,class:"p_input p_border" %>
                    </center>
               </div>

               <div class="sub_right">
                    <p class="p_title add_mt20">Types</p>
                         <%= f.text_field :type1, class:"p2_input p_border m_b", placeholder:"1 (required)" %>
                         <%= f.text_field :type2, class:"p2_input p_border m_b", placeholder:"2" %>
                    
                    <p class="p_title add_mt20">Moves</p>
                         <%= f.text_field :move1, class:"p2_input p_border", placeholder:"1 (required)" %>
                         <%= f.text_field :move2, class:"p2_input p_border", placeholder:"2" %>
                         <%= f.text_field :move3, class:"p2_input p_border m_b", placeholder:"3" %>
                         <%= f.text_field :move4, class:"p2_input p_border m_b", placeholder:"4" %>

                    <p class="p_title add_mt20">Weakness</p>
                         <%= f.text_field :weakness1, class:"p2_input p_border m_b", placeholder:"1 (required)" %>
                         <%= f.text_field :weakness2, class:"p2_input p_border m_b", placeholder:"1" %>
                    
                    <p class="p_title add_mt20">Evolution</p>
                         <%= f.text_field :evolution1, class:"p2_input p_border", placeholder:"1"%>
                         <%= f.text_field :evolution2, class:"p2_input p_border", placeholder:"2"%>
                         <center>
                         <%= f.text_field :evolution3, class:"p2_input p_border m_b", placeholder:"3",style:"float:none" %>
                         </center>
               </div>
          </div>

          <% end %>
     </div>
</div>

app/views/cools/index.html.erb
<div class="div_setting">
     <div class="main">
          <div class="sub_top">
               <a href="../welcome/index" class="button_link left index_special">Home</a>
               <%= link_to 'Register', new_cool_path, class:"button_link right index_special"%>
          </div>

          <div class="sub_bottom">
               <div class="p_thead">
                    <span class="p_span" style="padding-left:10px;padding-right:220px;">Pokemon</span>
                    <span class="p_span" style="padding-right:235px;">Trainer</span>
                    <span class="p_span">Action</span>
               </div>
               <div class="sub_table">
               <table class="table table-hover">
                    <tbody>
                         <% @cools.each do |cool| %>
                         <tr>
                         <td style="width:5%"><img src="" class="pokemon_profile_small"/></td>
                            <td style="width:32.5%"><%= cool.pokemon %></td>
                            <td style="width:32.5%"><%= cool.trainer %></td>
                            <td style="width:30%">
                              <!-- <a href="">Remove</a> -->
                              <%= link_to 'Destroy', cool_path(cool),method: :delete,data: { confirm: 'Are you sure?' } %>
                              <!-- <a href="">Edit</a> -->
                              <%= link_to 'Edit', edit_cool_path(cool) %>
                              <!-- <a href="">Show</a> -->
                              <%= link_to 'Show', cool_path(cool) %>
                            </td>
                         </tr>
                         <% end %>
                    </tbody>
               </table>
               </div>
          </div>
     </div>
</div>

app/views/cools/show.html.erb
<div class="div_setting">
     <div class="main">
          <div class="sub_top">
               <%= link_to 'Pokemon List', cools_path,  class:"button_link left"%>
               <%= link_to 'Edit', edit_cool_path(@cool), class:"button_link right" %>
          </div>

          <div class="sub_bottom">
               <div class="sub_left">
                    <img src="c.png" class="pokemon_profile"/>
                    <p class="p_title">Pokemon</p>
                    <p class="p_content add_mb20"><%= @cool.pokemon %></p>
                    <p class="p_title">Trainer</p>
                    <p class="p_content"><%= @cool.trainer %></p>
               </div>

               <div class="sub_right">
                    <div class="sub_rightcontent">
                         <div class="rightcontent_title p_title add_mb10">Types</div>
                         <div class="rightcontent">
                              <div class="rightcontent_main add_mb30"><%= @cool.type1 %></div>
                              <div class="rightcontent_main add_mb30"><%= @cool.type2 %></div>
                         </div>
                    </div>
                    <div class="sub_rightcontent">
                         <div class="rightcontent_title p_title add_mb10">Moves</div>
                         <div class="rightcontent">
                              <div class="rightcontent_main add_mb10"><%= @cool.move1 %></div>
                              <div class="rightcontent_main add_mb10"><%= @cool.move2 %></div>
                              <div class="rightcontent_main add_mb30"><%= @cool.move3 %></div>
                              <div class="rightcontent_main add_mb30"><%= @cool.move4 %></div>
                         </div>
                    </div>
                    <div class="sub_rightcontent">
                         <div class="rightcontent_title p_title add_mb10">Weaknesses</div>
                         <div class="rightcontent">
                              <div class="rightcontent_main add_mb30"><%= @cool.weakness1 %></div>
                              <div class="rightcontent_main add_mb30"><%= @cool.weakness2 %></div>
                         </div>
                    </div>
                    <div class="sub_rightcontent">
                         <div class="rightcontent_title p_title add_mb10">Evolution</div>
                         <div class="rightcontent">
                              <div class="rightcontent_main add_mb10"><%= @cool.evolution1 %></div>
                              <div class="rightcontent_main add_mb10"><%= @cool.evolution2 %></div>
                              <div class="rightcontent_main add_mb30"><%= @cool.evolution3 %></div>
                         </div>
                    </div>
               </div>
          </div>
     </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/smarts/edit.html.erb
<div class="div_setting">
     <div class="main">
          
          <%= form_for :smart, url: smart_path(@smart), method: :patch do |f| %>

          <div class="sub_top">
               <%= link_to 'Pokemon List', smarts_path,class:"button_link left"%>
               <%= f.submit "Save", class:"button_link right"%>         
          </div>
         
          <div class="sub_bottom">
               <div class="sub_left">
                    <img src="c.png" class="pokemon_profile"/>
                    <p class="p_title">Pokemon</p>
                    <center>
                         <%= f.text_field :pokemon, class:'p_input p_border add_mb20' %>
                    </center>
                    <p class="p_title">Trainer</p>
                    <center>
                         <%= f.text_field :trainer,class:"p_input p_border" %>
                    </center>
               </div>

               <div class="sub_right">
                    <p class="p_title add_mt20">Types</p>
                         <%= f.text_field :type1, class:"p2_input p_border m_b", placeholder:"1 (required)" %>
                         <%= f.text_field :type2, class:"p2_input p_border m_b", placeholder:"2" %>
                    
                    <p class="p_title add_mt20">Moves</p>
                         <%= f.text_field :move1, class:"p2_input p_border", placeholder:"1 (required)" %>
                         <%= f.text_field :move2, class:"p2_input p_border", placeholder:"2" %>
                         <%= f.text_field :move3, class:"p2_input p_border m_b", placeholder:"3" %>
                         <%= f.text_field :move4, class:"p2_input p_border m_b", placeholder:"4" %>

                    <p class="p_title add_mt20">Weakness</p>
                         <%= f.text_field :weakness1, class:"p2_input p_border m_b", placeholder:"1 (required)" %>
                         <%= f.text_field :weakness2, class:"p2_input p_border m_b", placeholder:"1" %>
                    
                    <p class="p_title add_mt20">Evolution</p>
                         <%= f.text_field :evolution1, class:"p2_input p_border", placeholder:"1"%>
                         <%= f.text_field :evolution2, class:"p2_input p_border", placeholder:"2"%>
                         <center>
                         <%= f.text_field :evolution3, class:"p2_input p_border m_b", placeholder:"3",style:"float:none" %>
                         </center>
               </div>
          </div>

          <% end %>
     </div>
</div>

app/views/smarts/index.html.erb
<div class="div_setting">
     <div class="main">
          <div class="sub_top">
               <a href="../welcome/index" class="button_link left index_special">Home</a>
               <%= link_to 'Register', new_smart_path, class:"button_link right index_special"%>
          </div>

          <div class="sub_bottom">
               <div class="p_thead">
                    <span class="p_span" style="padding-left:10px;padding-right:220px;">Pokemon</span>
                    <span class="p_span" style="padding-right:235px;">Trainer</span>
                    <span class="p_span">Action</span>
               </div>
               <div class="sub_table">
               <table class="table table-hover">
                    <tbody>
                         <% @smarts.each do |smart| %>
                         <tr>
                         <td style="width:5%"><img src="" class="pokemon_profile_small"/></td>
                            <td style="width:32.5%"><%= smart.pokemon %></td>
                            <td style="width:32.5%"><%= smart.trainer %></td>
                            <td style="width:30%">
                              <%= link_to 'Destroy', smart_path(smart),method: :delete,data: { confirm: 'Are you sure?' } %>
                              <%= link_to 'Edit', edit_smart_path(smart) %>
                              <%= link_to 'Show', smart_path(smart) %>
                            </td>
                         </tr>
                         <% end %>
                    </tbody>
               </table>
               </div>
          </div>
     </div>
</div>

app/views/smarts/new.html.erb
<div class="div_setting">
     <div class="main">
          <%= form_for :smart, url: smarts_path do |f| %>
          
          <div class="sub_top">
               <%= link_to 'Pokemon List', smarts_path,class:"button_link left"%>
               <%= f.submit "Save", class:"button_link right"%>         
          </div>
         
          <div class="sub_bottom">
               <div class="sub_left">
                    <img src="c.png" class="pokemon_profile"/>
                    <p class="p_title">Pokemon</p>
                    <center>
                         <%= f.text_field :pokemon, class:'p_input p_border add_mb20' %>
                    </center>
                    <p class="p_title">Trainer</p>
                    <center>
                         <%= f.text_field :trainer,class:"p_input p_border" %>
                    </center>
               </div>

               <div class="sub_right">
                    <p class="p_title add_mt20">Types</p>
                         <%= f.text_field :type1, class:"p2_input p_border m_b", placeholder:"1 (required)" %>
                         <%= f.text_field :type2, class:"p2_input p_border m_b", placeholder:"2" %>
                    
                    <p class="p_title add_mt20">Moves</p>
                         <%= f.text_field :move1, class:"p2_input p_border", placeholder:"1 (required)" %>
                         <%= f.text_field :move2, class:"p2_input p_border", placeholder:"2" %>
                         <%= f.text_field :move3, class:"p2_input p_border m_b", placeholder:"3" %>
                         <%= f.text_field :move4, class:"p2_input p_border m_b", placeholder:"4" %>

                    <p class="p_title add_mt20">Weakness</p>
                         <%= f.text_field :weakness1, class:"p2_input p_border m_b", placeholder:"1 (required)" %>
                         <%= f.text_field :weakness2, class:"p2_input p_border m_b", placeholder:"1" %>
                    
                    <p class="p_title add_mt20">Evolution</p>
                         <%= f.text_field :evolution1, class:"p2_input p_border", placeholder:"1"%>
                         <%= f.text_field :evolution2, class:"p2_input p_border", placeholder:"2"%>
                         <center>
                         <%= f.text_field :evolution3, class:"p2_input p_border m_b", placeholder:"3",style:"float:none" %>
                         </center>
               </div>
          </div>

          <% end %>
     </div>
</div>

app/views/smarts/show.html.erb
<div class="div_setting">
     <div class="main">
          <div class="sub_top">
               <%= link_to 'Pokemon List', smarts_path,  class:"button_link left"%>
               <%= link_to 'Edit', edit_smart_path(@smart), class:"button_link right" %>
          </div>

          <div class="sub_bottom">
               <div class="sub_left">
                    <img src="c.png" class="pokemon_profile"/>
                    <p class="p_title">Pokemon</p>
                    <p class="p_content add_mb20"><%= @smart.pokemon %></p>
                    <p class="p_title">Trainer</p>
                    <p class="p_content"><%= @smart.trainer %></p>
               </div>

               <div class="sub_right">
                    <div class="sub_rightcontent">
                         <div class="rightcontent_title p_title add_mb10">Types</div>
                         <div class="rightcontent">
                              <div class="rightcontent_main add_mb30"><%= @smart.type1 %></div>
                              <div class="rightcontent_main add_mb30"><%= @smart.type2 %></div>
                         </div>
                    </div>
                    <div class="sub_rightcontent">
                         <div class="rightcontent_title p_title add_mb10">Moves</div>
                         <div class="rightcontent">
                              <div class="rightcontent_main add_mb10"><%= @smart.move1 %></div>
                              <div class="rightcontent_main add_mb10"><%= @smart.move2 %></div>
                              <div class="rightcontent_main add_mb30"><%= @smart.move3 %></div>
                              <div class="rightcontent_main add_mb30"><%= @smart.move4 %></div>
                         </div>
                    </div>
                    <div class="sub_rightcontent">
                         <div class="rightcontent_title p_title add_mb10">Weaknesses</div>
                         <div class="rightcontent">
                              <div class="rightcontent_main add_mb30"><%= @smart.weakness1 %></div>
                              <div class="rightcontent_main add_mb30"><%= @smart.weakness2 %></div>
                         </div>
                    </div>
                    <div class="sub_rightcontent">
                         <div class="rightcontent_title p_title add_mb10">Evolution</div>
                         <div class="rightcontent">
                              <div class="rightcontent_main add_mb10"><%= @smart.evolution1 %></div>
                              <div class="rightcontent_main add_mb10"><%= @smart.evolution2 %></div>
                              <div class="rightcontent_main add_mb30"><%= @smart.evolution3 %></div>
                         </div>
                    </div>
               </div>
          </div>
     </div>
</div>

app/views/toughs/index.html.erb
<div class="div_setting">
     <div class="main">
          <div class="sub_top">
               <a href="../welcome/index" class="button_link left index_special">Home</a>
               <%= link_to 'Register', new_tough_path, class:"button_link right index_special"%>
          </div>

          <div class="sub_bottom">
               <div class="p_thead">
                    <span class="p_span" style="padding-left:10px;padding-right:220px;">Pokemon</span>
                    <span class="p_span" style="padding-right:235px;">Trainer</span>
                    <span class="p_span">Action</span>
               </div>
               <div class="sub_table">
               <table class="table table-hover">
                    <tbody>
                         <% @toughs.each do |tough| %>
                         <tr>
                         <td style="width:5%"><img src="" class="pokemon_profile_small"/></td>
                            <td style="width:32.5%"><%= tough.pokemon %></td>
                            <td style="width:32.5%"><%= tough.trainer %></td>
                            <td style="width:30%">
                              <%= link_to 'Destroy', tough_path(tough),method: :delete,data: { confirm: 'Are you sure?' } %>
                              <%= link_to 'Edit', edit_tough_path(tough) %>
                              <%= link_to 'Show', tough_path(tough) %>
                            </td>
                         </tr>
                         <% end %>
                    </tbody>
               </table>
               </div>
          </div>
     </div>
</div>